<a href="https://colab.research.google.com/github/Wonbin-Choi/OpenCV_practice/blob/main/Numpy%EC%9D%98_%EC%97%B0%EC%82%B0%EA%B3%BC_%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy의 기본연산

In [1]:
import numpy as np

array = np.random.randint(1,10,(2,2))
print(array)

[[7 3]
 [2 6]]


In [2]:
result_array = array * 10
print(result_array)

[[70 30]
 [20 60]]


### 서로 다른 형태의 Numpy 연산
- Numpy는 서로 다른 형태의 배열을 연산할 때는 행 우선으로 수행이 된다.

In [4]:
array1 = np.arange(4).reshape(2,2) # 2x2
array2 = np.arange(2) # 1x2
array3 = array1 + array2
print(array3)

[[0 2]
 [2 4]]


- 브로드캐스트: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

In [7]:
array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1,array2],axis=0) # 4x4
print(array3)
array4 = np.arange(0,4).reshape(4,1) # 4x1
print(array3+array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


### Numpy의 마스킹 연산
- 마스킹: 각 원소에 대하여 체크합니다.
- 마스킹 연산은 이미지 처리할 때 너무 밝거나 어두운 픽셀들만 다른 픽셀값으로 바꾸는 작업을 수행할 때 요긴하게 사용된다.

In [11]:
array1 = np.arange(16).reshape(4,4)
print(array1)
array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


### Numpy의 집계 함수

In [13]:
array = np.arange(16).reshape(4,4)
print(f"최댓값: {np.max(array)}")
print(f"최소값: {np.min(array)}")
print(f"합계: {np.sum(array)}")
print(f"평균: {np.mean(array)}")

최댓값: 15
최소값: 0
합계: 120
평균: 7.5


In [14]:
array = np.arange(16).reshape(4,4)
print(array)
print(f"합계: {np.sum(array,axis=0)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계: [24 28 32 36]
