<a href="https://colab.research.google.com/github/Wonbin-Choi/OpenCV_practice/blob/main/Numpy_%EA%B8%B0%EB%B3%B8_%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###List를 Numpy로 바꾸어 보기

In [ ]:
import numpy as np
arr = np.array([1,2,3]) # numpy 자료형으로 바꾼다
print(arr.size) # 배열의 크기
print(arr.dtype) # 배열 원소의 타입
print(arr[2])

3
int64
3


### Numpy 배열 초기화 하기

In [ ]:
import numpy as np
# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

# 0으로 초기화
array2 = np.zeros((4,4),dtype=float) # 4x4 행렬을 0으로 초기화
print(array2)

# 1로 초기화
array3 = np.ones((4,4),dtype=float) # 4x4 행렬을 1으로 초기화
print(array3)

# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0,10,(3,3)) # 0에서 10미만 3x3 행렬
print(array4)

# 평균이 0이고 표준편차가 1인 표준 정규 분포를 띄는 배열
array5 = np.random.normal(0,1,(3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4 3 3]
 [1 5 9]
 [3 9 2]]
[[ 1.73083144 -0.99999863 -0.88557593]
 [-0.16268566  0.06728659 -0.21787575]
 [ 0.21487224 -0.34646769  0.92664535]]


### Numpy 배열 합치기

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1,array2]) # 배열을 합칠 때 쓰는 concetenate

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


### Numpy 배열 형태 바꾸기

In [ ]:
import numpy as np

array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))
print(array2)
print(array2.shape)

[[1 2]
 [3 4]]
(2, 2)


### Numpy 배열 세로축으로 함치기

In [ ]:
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
array3 = np.concatenate([array1, array2],axis=0) # axis=0 이면 행 , 1 이면 열, 2 이면 channel
print(array3)

[[0 1 2 3 0 1 2 3]]


### Numpy 배열 나누기

In [ ]:
import numpy as np

array = np.arange(8).reshape(2,4)
left, right = np.split(array,[2],axis=1) # array를 index = 2인 열을 기준으로 나눈다.
print(left)
print(left.shape)
print(right)
print(right.shape)
print(right[1][1])

[[0 1]
 [4 5]]
(2, 2)
[[2 3]
 [6 7]]
(2, 2)
7
