<a href="https://colab.research.google.com/github/Wonbin-Choi/OpenCV_practice/blob/main/Numpy%EC%9D%98_%ED%99%9C%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Numpy의 저장과 불러오기

In [4]:
# 단일 객체 저장 및 불러오기
array = np.arange(0,10)
np.save("saved.npy",array)

result = np.load("saved.npy")
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# 복수 객체 저장 및 불러오기
array1 = np.arange(10)
array2 = np.arange(10,20)
np.savez("saved.npz",array1=array1, array2=array2)

data = np.load("saved.npz",)
result1 = data["array1"]
result2 = data["array2"]

print(result1, result2)

[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19]
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


### Numpy 원소의 정렬

In [13]:
# Numpy 원소 오름차순 정렬
array = np.array([5,9,10,3,1])
array.sort()
print(array)
print(array[::-1])

[ 1  3  5  9 10]
[10  9  5  3  1]


In [18]:
# 각 열을 기준으로 정렬
array = np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array)

array.sort(axis=0) # 같은 행끼리의 열중에 오름차순으로 정렬
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [24]:
# 균일한 간격으로 데이터를 생성
array = np.linspace(0,10,5) # 시작값과 끝값 사이에 몇개의 데이터가 있는지
print(array)

# 난수의 재연(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0,10,(2,3)))

# Numpy 배열 객체 복사
array1 = np.arange(0,10)
array2 = array1 # 얕은 복사,주소만 복사
array2[0] = 99
print(array1)

array1 = np.arange(0,10)
array2 = array1.copy() # 깊은 복사, 데이터를 복사
array2[0] = 99
print(array1)

# 중복된 원소 제거
array = np.array([1,1,2,2,3,3,4])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]
[99  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
